# k8 Deployment DB secret 
# In this way password will be injected at runtime only
apiVersion: v1
kind: Pod
metdata:
  name: postgress-client
spec: 
  containers:
    - name: db-client
      image: postgress
      env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef: 
              name: db-secret
              key: password


---
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  password: wyFbc98rnfllss      # base64 encoded pwd

# echo -n 'your password' |base64          