apiVersion: v1
kind: ServiceAccount
metadata:
  name: sample

---  

# Create a Role that allows reading pods in the default namespace

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: ns-read-only
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "list"]


---
# Role Binding to bind the Role to either a user or the ServiceAccount

apiVersion: rbac.authorization.k8s.io/v1
# This role binding allows "jane" to read pods in the "default" namespace.
# You need to already have a Role named "pod-reader" in that namespace.
kind: RoleBinding
metadata:
  name: ns-read-only
  namespace: default
subjects:
# You can specify more than one "subject"
- kind: ServiceAccount #this must be User, Group or ServiceAccount
  name: sample
  apiGroup: rbac.authorization.k8s.io
roleRef:
  # "roleRef" specifies the binding to a Role / ClusterRole
  kind: Role #this must be Role or ClusterRole
  name: ns-read-only # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io
