# Node Schduler Example with NodeSelector

apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
    - name: nginx
      image: nginx:perl
      ports:
        - containerPort: 80
  nodeSelector:
    disktype: ssd   # This Pod will be scheduled on nodes with the label disktype=ssd

    