apiVersion: v1  
kind: Namespace
metadata:
  name: expense

---

apiVersion: v1
kind: Pod
metadata:
  name: nginx-exp
  namespace: expense
spec:
  containers:
    - name: nginx
      image: nginx:perl


# kubectl get all            ----> To see all resources in the default namespace
# kubectl get all -n expense ----> To see all resources in the 'expense' namespace      