apiVersion: v1
kind: Secret
metadata:
  name: nginx-secret
data:
  db_user: "c2hyaXBhZAo="
  db_password: "c2hyaXBhZAo="
  api_token: "c2hyaXBhZAo="


---

apiVersion: v1
kind: Pod
metadata:
  name: nginx-cm
spec:
  containers:
    - name: nginx
      image: nginx:perl
      envFrom:
      - secretRef:
          name: nginx-secret
