apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-secret
data: 
  db_user: ""
  db_password: ""
  api_token: ""
  .secret_file: ""


---

apiVersion: v1
kind: Pod
metadata:
  name: nginx-cm
spec:
  containers:
    - name: nginx
      image: nginx:perl
      envFrom:
      - secretRef:
          name: nginx-secret

