apiVersion: v1
kind: secret
metadata:
  name: nginx-secret
data: 
  db_user: ""
  db_password: "cgein+bbb"
  api_token: ""
  .secret_file: ""


---

apiVersion: v1
kind: Pod
metadata:
  name: nginx-cm
spec:
  containers:
    - name: nginx
      image: nginx:perl
      envFrom:
      - secretKeyRef:
          name: nginx-secret
          key: db_password

